/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej3;

/**
 *
 * @author Lourdes
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        InicioSesion = new javax.swing.JDialog();
        panelPrincipal1 = new javax.swing.JPanel();
        panelSuperior1 = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        lblEslogan1 = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContras = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        fieldContras = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        Comunidad = new javax.swing.JDialog();
        panelPrincipal2 = new javax.swing.JPanel();
        panelSuperior2 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        lblEslogan2 = new javax.swing.JLabel();
        PanelCentral2 = new javax.swing.JPanel();
        lblComunidad = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldApellidos = new javax.swing.JTextField();
        fieldFecha = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        fieldPeso = new javax.swing.JTextField();
        fieldAltura = new javax.swing.JTextField();
        fieldDias = new javax.swing.JTextField();
        lblAmigos = new javax.swing.JLabel();
        btnAtras1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAmigos = new javax.swing.JTable();
        Menus = new javax.swing.JDialog();
        panelPrincipal3 = new javax.swing.JPanel();
        panelSuperior3 = new javax.swing.JPanel();
        lblLogo3 = new javax.swing.JLabel();
        lblEslogan3 = new javax.swing.JLabel();
        panelCentral2 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        btnAtras2 = new javax.swing.JButton();
        Empresa = new javax.swing.JDialog();
        panelPrincipal4 = new javax.swing.JPanel();
        panelSuperior4 = new javax.swing.JPanel();
        lblLogo4 = new javax.swing.JLabel();
        lblEslogan4 = new javax.swing.JLabel();
        panelCentral3 = new javax.swing.JPanel();
        lblEmpresa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSmile = new javax.swing.JLabel();
        lblSmile1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIg = new javax.swing.JLabel();
        lblRRSS = new javax.swing.JLabel();
        lblTw = new javax.swing.JLabel();
        lblRSS1 = new javax.swing.JLabel();
        lblFb = new javax.swing.JLabel();
        lblRSS2 = new javax.swing.JLabel();
        lblGmail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblEslogan = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnCom = new javax.swing.JButton();
        btnMenus = new javax.swing.JButton();
        btnConoc = new javax.swing.JButton();

        InicioSesion.setMinimumSize(new java.awt.Dimension(584, 380));

        panelPrincipal1.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal1.setLayout(new java.awt.BorderLayout());

        panelSuperior1.setBackground(new java.awt.Color(255, 204, 153));
        panelSuperior1.setPreferredSize(new java.awt.Dimension(400, 40));
        panelSuperior1.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/logo.png"))); // NOI18N
        panelSuperior1.add(lblLogo1);

        lblEslogan1.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblEslogan1.setForeground(new java.awt.Color(255, 255, 255));
        lblEslogan1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEslogan1.setText("¡Es hora de empezar a llevar una vida saludable!      ");
        panelSuperior1.add(lblEslogan1);

        panelPrincipal1.add(panelSuperior1, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setLayout(new java.awt.GridBagLayout());

        lblIniciarSesion.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 153, 0));
        lblIniciarSesion.setText("Iniciar Sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 10, 0, 0);
        panelCentral.add(lblIniciarSesion, gridBagConstraints);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 156, 0, 0);
        panelCentral.add(lblUsuario, gridBagConstraints);

        lblContras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContras.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 131, 0, 0);
        panelCentral.add(lblContras, gridBagConstraints);

        fieldUsuario.setText("manutr");
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 10, 0, 174);
        panelCentral.add(fieldUsuario, gridBagConstraints);

        fieldContras.setText("12345678");
        fieldContras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 174);
        panelCentral.add(fieldContras, gridBagConstraints);

        btnLogIn.setText("Log In");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 1, 53, 0);
        panelCentral.add(btnLogIn, gridBagConstraints);

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 47, 53, 0);
        panelCentral.add(btnAtras, gridBagConstraints);

        panelPrincipal1.add(panelCentral, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout InicioSesionLayout = new javax.swing.GroupLayout(InicioSesion.getContentPane());
        InicioSesion.getContentPane().setLayout(InicioSesionLayout);
        InicioSesionLayout.setHorizontalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InicioSesionLayout.setVerticalGroup(
            InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Comunidad.setMinimumSize(new java.awt.Dimension(600, 490));

        panelPrincipal2.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal2.setMinimumSize(new java.awt.Dimension(610, 490));
        panelPrincipal2.setPreferredSize(new java.awt.Dimension(610, 490));
        panelPrincipal2.setLayout(new java.awt.BorderLayout());

        panelSuperior2.setBackground(new java.awt.Color(255, 204, 153));
        panelSuperior2.setPreferredSize(new java.awt.Dimension(400, 40));
        panelSuperior2.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/logo.png"))); // NOI18N
        panelSuperior2.add(lblLogo2);

        lblEslogan2.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblEslogan2.setForeground(new java.awt.Color(255, 255, 255));
        lblEslogan2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEslogan2.setText("¡Es hora de empezar a llevar una vida saludable!      ");
        panelSuperior2.add(lblEslogan2);

        panelPrincipal2.add(panelSuperior2, java.awt.BorderLayout.PAGE_START);

        PanelCentral2.setBackground(new java.awt.Color(255, 255, 255));
        PanelCentral2.setMinimumSize(new java.awt.Dimension(600, 490));
        PanelCentral2.setPreferredSize(new java.awt.Dimension(600, 490));
        PanelCentral2.setLayout(new java.awt.GridBagLayout());

        lblComunidad.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblComunidad.setForeground(new java.awt.Color(255, 153, 0));
        lblComunidad.setText("Comunidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 16, 0, 0);
        PanelCentral2.add(lblComunidad, gridBagConstraints);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        PanelCentral2.add(lblNombre, gridBagConstraints);

        lblApellidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 16, 0, 0);
        PanelCentral2.add(lblApellidos, gridBagConstraints);

        lblFecha.setText("Fecha de nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 16, 0, 0);
        PanelCentral2.add(lblFecha, gridBagConstraints);

        fieldNombre.setText("Manuel");
        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        PanelCentral2.add(fieldNombre, gridBagConstraints);

        fieldApellidos.setText("Troncoso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 0);
        PanelCentral2.add(fieldApellidos, gridBagConstraints);

        fieldFecha.setText("09-09-99");
        fieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        PanelCentral2.add(fieldFecha, gridBagConstraints);

        lblPeso.setText("Peso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 61, 0, 0);
        PanelCentral2.add(lblPeso, gridBagConstraints);

        lblAltura.setText("Altura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 61, 0, 0);
        PanelCentral2.add(lblAltura, gridBagConstraints);

        lblDias.setText("Días conseguidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 61, 0, 0);
        PanelCentral2.add(lblDias, gridBagConstraints);

        fieldPeso.setText("99 kg");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 25;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        PanelCentral2.add(fieldPeso, gridBagConstraints);

        fieldAltura.setText("1,90 m");
        fieldAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAlturaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 25;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        PanelCentral2.add(fieldAltura, gridBagConstraints);

        fieldDias.setText("29");
        fieldDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDiasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 1, 0, 0);
        PanelCentral2.add(fieldDias, gridBagConstraints);

        lblAmigos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblAmigos.setForeground(new java.awt.Color(255, 153, 0));
        lblAmigos.setText("Lista de amigos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 16, 0, 0);
        PanelCentral2.add(lblAmigos, gridBagConstraints);

        btnAtras1.setText("Atrás");
        btnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 106, 27, 0);
        PanelCentral2.add(btnAtras1, gridBagConstraints);

        tablaAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"anart", "20", "21"},
                {"luismh", "34", "10"},
                {"pedrott", "21", "5"},
                {"saravf", "18", "34"},
                {"raulpm", "30", "22"}
            },
            new String [] {
                "Usuario", "Edad", "Días conseguidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAmigos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 52;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 536;
        gridBagConstraints.ipady = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 0, 35);
        PanelCentral2.add(jScrollPane1, gridBagConstraints);

        panelPrincipal2.add(PanelCentral2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout ComunidadLayout = new javax.swing.GroupLayout(Comunidad.getContentPane());
        Comunidad.getContentPane().setLayout(ComunidadLayout);
        ComunidadLayout.setHorizontalGroup(
            ComunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ComunidadLayout.setVerticalGroup(
            ComunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menus.setMinimumSize(new java.awt.Dimension(700, 335));

        panelPrincipal3.setMinimumSize(new java.awt.Dimension(670, 445));
        panelPrincipal3.setPreferredSize(new java.awt.Dimension(670, 445));
        panelPrincipal3.setLayout(new java.awt.BorderLayout());

        panelSuperior3.setBackground(new java.awt.Color(255, 204, 153));
        panelSuperior3.setPreferredSize(new java.awt.Dimension(400, 40));
        panelSuperior3.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/logo.png"))); // NOI18N
        panelSuperior3.add(lblLogo3);

        lblEslogan3.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblEslogan3.setForeground(new java.awt.Color(255, 255, 255));
        lblEslogan3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEslogan3.setText("¡Es hora de empezar a llevar una vida saludable!      ");
        panelSuperior3.add(lblEslogan3);

        panelPrincipal3.add(panelSuperior3, java.awt.BorderLayout.PAGE_START);

        panelCentral2.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral2.setLayout(new java.awt.GridBagLayout());

        lblMenu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 153, 0));
        lblMenu.setText("Menús de la semana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 27, 0, 0);
        panelCentral2.add(lblMenu, gridBagConstraints);

        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Lunes", "Tostada", "Menestra", "Yogur", "Ensalada"},
                {"Martes", "Cereales", "Ensalada", "Fruta", "Puré"},
                {"Miércoles", "Tostada", "Cocido", "Bocadillo", "Sopa"},
                {"Jueves", "Fruta", "Arroz", "Cuajada", "Tortilla"},
                {"Viernes", "Galletas", "Legumbres", "Fruta", "Crepes jamón"},
                {"Sábado", "Yogur", "Puré", "Frutos secos", "Pescado"},
                {"Domingo", "Bizcocho", "Hamburguesa", "Galletas", "Puré"}
            },
            new String [] {
                "Día", "Desayuno", "Almuerzo", "Merienda", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaMenu.setShowGrid(true);
        jScrollPane2.setViewportView(tablaMenu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 619;
        gridBagConstraints.ipady = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 18);
        panelCentral2.add(jScrollPane2, gridBagConstraints);

        btnAtras2.setText("Atrás");
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 58, 23, 0);
        panelCentral2.add(btnAtras2, gridBagConstraints);

        panelPrincipal3.add(panelCentral2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout MenusLayout = new javax.swing.GroupLayout(Menus.getContentPane());
        Menus.getContentPane().setLayout(MenusLayout);
        MenusLayout.setHorizontalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        MenusLayout.setVerticalGroup(
            MenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, Short.MAX_VALUE)
        );

        Empresa.setMinimumSize(new java.awt.Dimension(600, 350));

        panelPrincipal4.setMinimumSize(new java.awt.Dimension(600, 350));
        panelPrincipal4.setPreferredSize(new java.awt.Dimension(600, 350));
        panelPrincipal4.setLayout(new java.awt.BorderLayout());

        panelSuperior4.setBackground(new java.awt.Color(255, 204, 153));
        panelSuperior4.setPreferredSize(new java.awt.Dimension(400, 40));
        panelSuperior4.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/logo.png"))); // NOI18N
        panelSuperior4.add(lblLogo4);

        lblEslogan4.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblEslogan4.setForeground(new java.awt.Color(255, 255, 255));
        lblEslogan4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEslogan4.setText("¡Es hora de empezar a llevar una vida saludable!      ");
        panelSuperior4.add(lblEslogan4);

        panelPrincipal4.add(panelSuperior4, java.awt.BorderLayout.PAGE_START);

        panelCentral3.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral3.setLayout(new java.awt.GridBagLayout());

        lblEmpresa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(255, 153, 0));
        lblEmpresa.setText("Sobre nosotros");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 36, 0, 0);
        panelCentral3.add(lblEmpresa, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("¡Gracias por descargar nuestra App!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 4, 0, 0);
        panelCentral3.add(jLabel1, gridBagConstraints);

        lblSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/smile.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 6, 0, 0);
        panelCentral3.add(lblSmile, gridBagConstraints);

        lblSmile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/smile.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 16, 0, 0);
        panelCentral3.add(lblSmile1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelCentral3.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("En Bee-healthy queremos animar a la sociedad a tomar conciencia sobre su salud.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 36, 0, 51);
        panelCentral3.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Para ello, esta aplicación te ayudará a crear un menú semanal según edad, peso,");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 36, 0, 0);
        panelCentral3.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("altura...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 36, 0, 0);
        panelCentral3.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("¡Añade a tus familiares y amigos!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 36, 0, 0);
        panelCentral3.add(jLabel8, gridBagConstraints);

        lblIg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/instagram.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 0, 0);
        panelCentral3.add(lblIg, gridBagConstraints);

        lblRRSS.setText("beehealthy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        panelCentral3.add(lblRRSS, gridBagConstraints);

        lblTw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/twitter.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        panelCentral3.add(lblTw, gridBagConstraints);

        lblRSS1.setText("beehealthy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 31, 0);
        panelCentral3.add(lblRSS1, gridBagConstraints);

        lblFb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/facebook.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        panelCentral3.add(lblFb, gridBagConstraints);

        lblRSS2.setText("beehealthy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 31, 0);
        panelCentral3.add(lblRSS2, gridBagConstraints);

        lblGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/gmail.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 66, 31, 0);
        panelCentral3.add(lblGmail, gridBagConstraints);

        lblEmail.setText("beehealthy@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 38;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 31, 51);
        panelCentral3.add(lblEmail, gridBagConstraints);

        panelPrincipal4.add(panelCentral3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout EmpresaLayout = new javax.swing.GroupLayout(Empresa.getContentPane());
        Empresa.getContentPane().setLayout(EmpresaLayout);
        EmpresaLayout.setHorizontalGroup(
            EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EmpresaLayout.setVerticalGroup(
            EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(255, 204, 153));
        panelSuperior.setPreferredSize(new java.awt.Dimension(400, 40));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ej3/images/logo.png"))); // NOI18N
        panelSuperior.add(lblLogo);

        lblEslogan.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        lblEslogan.setForeground(new java.awt.Color(255, 255, 255));
        lblEslogan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEslogan.setText("¡Es hora de empezar a llevar una vida saludable!      ");
        panelSuperior.add(lblEslogan);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelBotones.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        btnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 153, 0));
        btnIniciar.setText("INICIAR SESIÓN");
        btnIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.setOpaque(true);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelBotones.add(btnIniciar);

        btnCom.setBackground(new java.awt.Color(255, 255, 255));
        btnCom.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnCom.setForeground(new java.awt.Color(255, 153, 0));
        btnCom.setText("COMUNIDAD");
        btnCom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCom.setContentAreaFilled(false);
        btnCom.setOpaque(true);
        btnCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComActionPerformed(evt);
            }
        });
        panelBotones.add(btnCom);

        btnMenus.setBackground(new java.awt.Color(255, 255, 255));
        btnMenus.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnMenus.setForeground(new java.awt.Color(255, 153, 0));
        btnMenus.setText("MENÚS");
        btnMenus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenus.setContentAreaFilled(false);
        btnMenus.setOpaque(true);
        btnMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenusActionPerformed(evt);
            }
        });
        panelBotones.add(btnMenus);

        btnConoc.setBackground(new java.awt.Color(255, 255, 255));
        btnConoc.setForeground(new java.awt.Color(255, 153, 0));
        btnConoc.setText("CONÓCENOS");
        btnConoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConoc.setContentAreaFilled(false);
        btnConoc.setOpaque(true);
        btnConoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConocActionPerformed(evt);
            }
        });
        panelBotones.add(btnConoc);

        panelPrincipal.add(panelBotones, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        InicioSesion.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        InicioSesion.setModal(true);
        InicioSesion.setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras1ActionPerformed
        // TODO add your handling code here:
        Comunidad.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnAtras1ActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        // TODO add your handling code here:
        Menus.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btnComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComActionPerformed
        // TODO add your handling code here:
        Comunidad.setModal(true);
        Comunidad.setVisible(true);
    }//GEN-LAST:event_btnComActionPerformed

    private void btnMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenusActionPerformed
        // TODO add your handling code here:
        Menus.setModal(true);
        Menus.setVisible(true);
    }//GEN-LAST:event_btnMenusActionPerformed

    private void btnConocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConocActionPerformed
        // TODO add your handling code here:
        Empresa.setModal(true);
        Empresa.setVisible(true);
    }//GEN-LAST:event_btnConocActionPerformed

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void fieldContrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContrasActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFechaActionPerformed

    private void fieldAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAlturaActionPerformed

    private void fieldDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Comunidad;
    private javax.swing.JDialog Empresa;
    private javax.swing.JDialog InicioSesion;
    private javax.swing.JDialog Menus;
    private javax.swing.JPanel PanelCentral2;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnCom;
    private javax.swing.JButton btnConoc;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnMenus;
    private javax.swing.JTextField fieldAltura;
    private javax.swing.JTextField fieldApellidos;
    private javax.swing.JPasswordField fieldContras;
    private javax.swing.JTextField fieldDias;
    private javax.swing.JTextField fieldFecha;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPeso;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAmigos;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblComunidad;
    private javax.swing.JLabel lblContras;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEslogan;
    private javax.swing.JLabel lblEslogan1;
    private javax.swing.JLabel lblEslogan2;
    private javax.swing.JLabel lblEslogan3;
    private javax.swing.JLabel lblEslogan4;
    private javax.swing.JLabel lblFb;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGmail;
    private javax.swing.JLabel lblIg;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblLogo4;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRRSS;
    private javax.swing.JLabel lblRSS1;
    private javax.swing.JLabel lblRSS2;
    private javax.swing.JLabel lblSmile;
    private javax.swing.JLabel lblSmile1;
    private javax.swing.JLabel lblTw;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelCentral2;
    private javax.swing.JPanel panelCentral3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPrincipal1;
    private javax.swing.JPanel panelPrincipal2;
    private javax.swing.JPanel panelPrincipal3;
    private javax.swing.JPanel panelPrincipal4;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelSuperior1;
    private javax.swing.JPanel panelSuperior2;
    private javax.swing.JPanel panelSuperior3;
    private javax.swing.JPanel panelSuperior4;
    private javax.swing.JTable tablaAmigos;
    private javax.swing.JTable tablaMenu;
    // End of variables declaration//GEN-END:variables
}
